name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_PETZY_HOST }}
          username: ${{ secrets.SERVER_PETZY_USER }}
          key: ${{ secrets.SERVER_PETZY_SSH_KEY }}
          script: |
            echo "--- Debug Info ---"
            pwd
            ls -la
            echo "--- Navigating to project ---"
            cd ~/services/cat-health-control || cd ~/cat-health-control || (echo "Project folder not found!" && exit 1)
            pwd
            ls -la
            echo "--- Deployment ---"
            git pull origin master
            docker compose build frontend
            docker compose up -d --remove-orphans
            docker compose ps
